import assert from 'node:assert/strict';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import test from 'node:test';
import { bundleExternalReferences } from '@prauga/flexdoc-client';
import yaml from 'js-yaml';
import { buildSite, serveSite } from '../src/cli.js';

const testDir = dirname(fileURLToPath(import.meta.url));
const cliDir = resolve(testDir, '..');
const repoRoot = resolve(cliDir, '../..');
const fixtureDir = join(testDir, 'fixtures');
const fixture = join(fixtureDir, 'openapi.yaml');
process.env.FLEXDOC_CLIENT_DIR = join(repoRoot, 'packages/client');

async function temp(name) {
  const root = join(tmpdir(), `flexdoc-cli-${process.pid}-${name}`);
  await rm(root, { recursive: true, force: true });
  await mkdir(root, { recursive: true });
  return root;
}

async function loadYamlFile(path) {
  return yaml.load(await readFile(path, 'utf8'));
}

test('build creates a deployable static site and bundles nested external refs', async () => {
  const root = await temp('build');
  const out = join(root, 'site');
  try {
    await buildSite(fixture, { out, basePath: '/docs/', title: 'Exported API' });
    const [html, js, css, specText] = await Promise.all([
      readFile(join(out, 'index.html'), 'utf8'),
      readFile(join(out, 'flexdoc.js'), 'utf8'),
      readFile(join(out, 'flexdoc.css'), 'utf8'),
      readFile(join(out, 'openapi.json'), 'utf8'),
    ]);
    assert.match(html, /<title>Exported API<\/title>/);
    assert.match(html, /href="\/docs\/flexdoc.css"/);
    assert.match(html, /src="\/docs\/flexdoc.js"/);
    assert.ok(js.length > 1000);
    assert.ok(css.length > 100);

    const spec = JSON.parse(specText);
    assert.equal(spec.info.title, 'Exported API');
    assert.ok(spec['x-flexdoc-external-documents']);
    const externalDocs = Object.values(spec['x-flexdoc-external-documents']);
    assert.equal(externalDocs.length, 2);
    const responseRef = spec.paths['/pets/{id}'].get.responses['200'].content['application/json'].schema.$ref;
    assert.match(responseRef, /^#\/x-flexdoc-external-documents\//);
    assert.ok(externalDocs.some((doc) => doc.$defs?.Pet));
    assert.ok(externalDocs.some((doc) => doc.$defs?.Tag));
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test('CLI build output exactly matches the client OpenAPI bundler', async () => {
  const root = await temp('parity');
  const out = join(root, 'site');
  try {
    const rootSpec = await loadYamlFile(fixture);
    const rootUri = pathToFileURL(fixture).toString();
    const clientBundled = await bundleExternalReferences(rootSpec, {
      baseUri: rootUri,
      load: async (uri) => loadYamlFile(fileURLToPath(uri)),
    });

    await buildSite(fixture, { out });
    const cliBundled = JSON.parse(await readFile(join(out, 'openapi.json'), 'utf8'));
    assert.deepEqual(cliBundled, clientBundled);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test('build protects non-FlexDoc output directories unless --force is used', async () => {
  const root = await temp('overwrite');
  const out = join(root, 'site');
  try {
    await mkdir(out, { recursive: true });
    await writeFile(join(out, 'keep.txt'), 'do not delete');
    await assert.rejects(() => buildSite(fixture, { out }), /Use --force/);
    await buildSite(fixture, { out, force: true });
    await assert.rejects(() => readFile(join(out, 'keep.txt')), { code: 'ENOENT' });
    assert.match(await readFile(join(out, '.flexdoc-generated'), 'utf8'), /Generated by/);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test('invalid root documents fail clearly', async () => {
  const root = await temp('invalid');
  const input = join(root, 'invalid.yaml');
  try {
    await writeFile(input, 'openapi: 3.1.0\ninfo:\n  title: Broken\n  version: 1\n');
    await assert.rejects(() => buildSite(input, { out: join(root, 'site') }), /expected openapi, info, and paths/);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test('serve hosts the generated site at a base path on an ephemeral port', async () => {
  const instance = await serveSite(fixture, { host: '127.0.0.1', port: 0, basePath: '/reference/' });
  try {
    const index = await fetch(instance.url);
    assert.equal(index.status, 200);
    assert.match(await index.text(), /CLI Fixture API/);
    const spec = await fetch(`${instance.url}openapi.json`);
    assert.equal(spec.status, 200);
    assert.equal((await spec.json()).info.title, 'CLI Fixture API');
    assert.equal((await fetch(new URL('/not-flexdoc', instance.url))).status, 404);
  } finally {
    await instance.close();
  }
});
