name: Publish Backend to npm Registry

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., patch, minor, major, or specific version)'
        required: true
        default: 'patch'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build -w packages/backend

      - name: Update package.json for npm registry
        run: |
          cd packages/backend
          # Remove GitHub specific publishConfig if present
          sed -i '/"publishConfig": {/,/}/d' package.json

      - name: Version and publish (on manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd packages/backend
          # Only update version if it's different from current version
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          if [ "$CURRENT_VERSION" != "${{ github.event.inputs.version }}" ]; then
            npm version ${{ github.event.inputs.version }} --no-git-tag-version
          fi
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish on release
        if: github.event_name == 'release'
        run: |
          cd packages/backend
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
